// Autor:     Antonio Carrillo Ledesma.
// R.F.C.:    CALA-691229-TV5
// Dirección: Amsterdam 312 col. Hipodromo Condesa
// Teléfono:  5-74-43-53

// Propiedad intelectual, todos los derechos reservados conforme a la ley, registro en tr mite
// Revisión  1.0-A

#ifndef TRAYEC_H
#define TRAYEC_H


// Archivo de configuracion
#define  CONFIGURACION  "C:\\CLOCK\\ALARMA.CFG"

// Archivos de solo lectura
#define  AYUDA_ALARMA   "C:\\CLOCK\\ALARMA.HLP"

// Archivo de alarmas
#define  ALARMAS        "C:\\CLOCK\\ARCHIVOS\\ALARMAS.DAT"


#endif
